version: '2'
services:
  
  ### web servers

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./store/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    build: letsencrypt/
    image: andrewmacheret/docker-letsencrypt-nginx-proxy-companion
    #image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - ./store/certs:/etc/nginx/certs:rw
      - ./store/letsencrypt:/etc/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"

  ### databases

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    #ports:
    #  - "3306:3306"
    volumes:
      - ./store/mysql:/var/lib/mysql
    hostname: mysql

  #mongo:
  #  image: mongo:3.2
  #  ports:
  #    - "27017:27017"
  #  volumes:
  #    - ./store/mongo:/data/db
  #  hostname: mongo

  ### functional servers

  #chess:
  #  build: chess-server/
  #  image: andrewmacheret/chess-server
  #  environment:
  #    VIRTUAL_HOST: chess.andrewmacheret.com
  #    LETSENCRYPT_HOST: chess.andrewmacheret.com
  #    LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  montyhall:
    image: andrewmacheret/montyhall-server
    environment:
      VIRTUAL_HOST: montyhall.andrewmacheret.com
      LETSENCRYPT_HOST: montyhall.andrewmacheret.com
      LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  vta-tracker:
    build: vta-tracker-server/
    image: andrewmacheret/vta-tracker-server
    volumes:
      - ./store/vta-tracker:/store
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      VIRTUAL_HOST: vta-tracker.andrewmacheret.com
      LETSENCRYPT_HOST: vta-tracker.andrewmacheret.com
      LETSENCRYPT_EMAIL: andrew.macheret@gmail.com
    external_links:
      - mysql

  #remote-apis:
  #  build: remote-apis/
  #  image: andrewmacheret/remote-apis
  #  environment:
  #    VIRTUAL_HOST: remote-apis.andrewmacheret.com
  #    LETSENCRYPT_HOST: remote-apis.andrewmacheret.com
  #    LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  ascii-cow:
    build: ascii-cow/
    image: andrewmacheret/ascii-cow
    environment:
      VIRTUAL_HOST: ascii-cow.andrewmacheret.com
      LETSENCRYPT_HOST: ascii-cow.andrewmacheret.com
      LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  #pun:
  #  build: pun-server/
  #  image: andrewmacheret/pun-server
  #  environment:
  #    VIRTUAL_HOST: pun.andrewmacheret.com
  #    LETSENCRYPT_HOST: pun.andrewmacheret.com
  #    LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  #pun-to-text:
  #  build: pun-to-text/
  #  image: andrewmacheret/pun-to-text
  #  environment:
  #    AWS_PARTITION: "aws"
  #    AWS_REGION: "us-east-1"
  #    AWS_ACCOUNT_ID: "515875352897"
  #    CRON: "0 9 * * * /root/send_pun.sh a1; 0 9 * * * /root/send_pun.sh mjc"

  #nhl:
  #  build: nhl-server/
  #  image: andrewmacheret/nhl-server
  #  environment:
  #    VIRTUAL_HOST: nhl.andrewmacheret.com
  #    LETSENCRYPT_HOST: nhl.andrewmacheret.com
  #    LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  temperature-sensor:
    image: andrewmacheret/temperature-sensor-server
    volumes:
      - ./data:/data
    ports:
      - "9030:30/udp"
    environment:
      VIRTUAL_HOST: temperature-sensor.andrewmacheret.com
      LETSENCRYPT_HOST: temperature-sensor.andrewmacheret.com
      LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

  stride-tabletop:
    image: andrewmacheret/stride-tabletop
    volumes:
      - ./store/stride-tabletop:/data
    environment:
      GAME_AI_URL: "${TABLETOP_GAME_AI_URL}"
      GAME_API_URL: "${TABLETOP_GAME_API_URL}"
      GAME_API_KEY: "${TABLETOP_GAME_API_KEY}"
      STRIDE_CLIENT_ID: "${TABLETOP_STRIDE_CLIENT_ID}"
      STRIDE_SECRET_ID: "${TABLETOP_STRIDE_SECRET_ID}"
      STORE_DIRECTORY: "/data"
      PORT: "80"
      VIRTUAL_HOST: stride-tabletop.andrewmacheret.com
      LETSENCRYPT_HOST: stride-tabletop.andrewmacheret.com
      LETSENCRYPT_EMAIL: andrew.macheret@gmail.com

